# CUDA 10.2 doesn't support GCC 9
c_compiler_version:            # [linux]
  - 10                          # [linux]
cxx_compiler_version:          # [linux]
  - 10                          # [linux]
